matter-js/python-matter-server

- README.md
Add instructions to README on how to release a new version of Python Matter Server.
> Add version bump instructions

- custom_components/matter_experimental/entity.py
We allowed storing but didn't set the entity description
> Set entity description

- tests/matter_experimental/common.py
Address [comments by @MartinHjelmare on #43](https://github.com/home-assistant-libs/python-matter-server/pull/43#pullrequestreview-1024292158)
> Address comments on test refactor

- custom_components/matter_experimental/binary_sensor.py
- custom_components/matter_experimental/entity.py
- custom_components/matter_experimental/sensor.py
- requirements-test.txt
- tests/fixtures/nodes_in_ha/fake-bridge-two-light.json
- tests/fixtures/nodes_in_ha/fake-temperature-sensor.json
- tests/fixtures/nodes_in_ha/fake_flow_sensor.json
- tests/fixtures/nodes_in_ha/fake_humidity_sensor.json
- tests/fixtures/nodes_in_ha/fake_light_sensor.json
- tests/fixtures/nodes_in_ha/fake_pressure_sensor.json
- tests/fixtures/nodes_in_ha/lighting-example-app.json
https://developers.home-assistant.io/blog/2022/07/10/entity_naming
> Switch to entity naming

- custom_components/matter_experimental/light.py
- scripts/show_stored_node.py
- tests/matter_experimental/common.py
- tests/matter_experimental/test_light.py
- tests/matter_experimental/test_mapping.py
- tests/test_utils/__init__.py
- tests/test_utils/mock_matter.py
> Always send transitionTime when sending MoveToLevelWithOnOff 

- .gitignore
- matter_server/client/client.py
- matter_server/common/models/api_command.py
- matter_server/common/models/node.py
- matter_server/server/device_controller.py
- matter_server/server/storage.py
some follow up things discovered while working on the integration
> Follow up after refactor

- matter_server/client/client.py
- matter_server/common/helpers/util.py
- matter_server/common/models/message.py
- matter_server/common/models/node.py
- matter_server/common/models/server_information.py
- matter_server/server/device_controller.py
Handle some more (de)serialization issues I discovered while testing with HA core.
> Handle (de)serialization issues

- .github/workflows/test.yml
- matter_server/client/__init__.py
- matter_server/client/client.py
- matter_server/common/helpers/api.py
- matter_server/common/helpers/json.py
- matter_server/common/helpers/util.py
- matter_server/common/models/device_type_instance.py
- matter_server/common/models/device_types.py
- matter_server/common/models/error.py
- matter_server/common/models/message.py
- matter_server/common/models/node.py
- matter_server/common/models/server_information.py
- matter_server/server/__main__.py
- matter_server/server/client_handler.py
- matter_server/server/device_controller.py
- matter_server/server/server.py
- matter_server/server/stack.py
- matter_server/server/storage.py
- pyproject.toml
- scripts/dump_fixer.py
- scripts/example.py
quick sweep for code quality and inting issues
> Code quality fixes

- matter_server/client/__init__.py
- matter_server/server/__init__.py
> Use all instead of disabling flake8

- pyproject.toml
- requirements-test.txt
- Remove not used custom component test requirement.
- Add pytest as it's needed for existing tests.
- Sort requirements.
> Clean requirements

- matter_server/server/device_controller.py
The commission on network command raised an exception with the same message as the commission with code command. Fix that.
> Fix commission on network exception message

- main.py
- matter_server/__init__.py
- matter_server/common/__init__.py
- matter_server/common/helpers/json.py
- matter_server/common/models/__init__.py
- matter_server/common/models/device_type_instance.py
- matter_server/common/models/message.py
- matter_server/common/models/node.py
- matter_server/common/models/node_device.py
- matter_server/server/device_controller.py
- pyproject.toml
- requirements-test.txt
- scripts/dump_fixer.py
- scripts/example.py
- scripts/generate_devices.py
- Add flake8-docstrings linter.
- Fix docstrings in matter server package.
> Lint docstrings

- .gitignore
- Add standard Python gitignore.
- Ignore vscode settings.
> Add standard Python gitignore

- matter_server/client/client.py
- matter_server/common/helpers/api.py
- matter_server/common/helpers/util.py
- matter_server/common/models/device_type_instance.py
- matter_server/common/models/node.py
- matter_server/server/client_handler.py
- matter_server/server/device_controller.py
- matter_server/server/server.py
- matter_server/server/stack.py
- scripts/example.py
- scripts/generate_devices.py
> Fix spelling

- .github/workflows/test.yml
- matter_server/common/helpers/api.py
- pyproject.toml
- requirements-test.txt
- tests/server/__init__.py
- tests/server/test_server.py
- Add server tests.
- Activate server tests in CI.
- Fix `parse_arguments` optional args.
> Add server test foundation

- docker-compose.yml
- Restart container unless stopped.
> Allow stopping docker container

- .github/workflows/test.yml
- matter_server/client/client.py
- matter_server/common/helpers/api.py
- matter_server/common/helpers/util.py
- matter_server/common/models/device_type_instance.py
- matter_server/common/models/node.py
- matter_server/server/__main__.py
- matter_server/server/client_handler.py
- matter_server/server/device_controller.py
- matter_server/server/server.py
- matter_server/server/storage.py
- pyproject.toml
- requirements-test.txt
- Move towards complete type annotations.
- Add py.typed.
- Add mypy during CI.
> Type package

- matter_server/client/client.py
- Fix inconsistent typing of the client subscribe method and related objects.
> Clean subscribe and signal event typing

- docker-compose.yml
- We're using host network_mode now.
> Remove docker port mapping

- matter_server/server/device_controller.py
- This was fixed in #149 but was lost when rebasing #141.
> Fix non awaited coroutine lingering again

- README.md
and slight change of some existing commands
> Additional commands for the documentation

- pyproject.toml
Include a small patch for python 3.11 compatibility
> Bump SDK wheels to 2023.2.1

- .github/workflows/test.yml
- .pre-commit-config.yaml
- matter_server/client/client.py
- matter_server/client/connection.py
- matter_server/client/models/device_types.py
- matter_server/client/models/node.py
- matter_server/common/errors.py
- matter_server/common/helpers/api.py
- matter_server/common/helpers/json.py
- matter_server/common/helpers/util.py
- matter_server/common/models.py
- matter_server/server/__main__.py
- matter_server/server/client_handler.py
- matter_server/server/const.py
- matter_server/server/device_controller.py
- matter_server/server/helpers/paa_certificates.py
- matter_server/server/server.py
- matter_server/server/stack.py
- matter_server/server/storage.py
- pyproject.toml
- requirements-test.txt
- scripts/beautify_diagnostics.py
- scripts/example.py
- scripts/generate_devices.py
- setup.cfg
This reverts commit 5b94974fff9ee6f0d6d9cbab0abf334d73e9fe9c.
As discussed, we'll fix the lint issues and tests in a small PR and do the other changes separately.
> Revert "Fix all lint issues (#245)"

- matter_server/server/device_controller.py
> fix fallback subscriptions for old HA versions

- compose.yml
> Fix image name in compose.yml

- matter_server/client/client.py
- matter_server/common/models.py
- matter_server/server/device_controller.py
Forward node events to process as Event entities in HA
> Allow forwarding Node Events

- README.md
> Correct example for sending a command, format JSON examples

- matter_server/client/client.py
- matter_server/client/models/device_types.py
- matter_server/client/models/node.py
- matter_server/common/helpers/util.py
- matter_server/server/device_controller.py
- pyproject.toml
- scripts/generate_devices.py
- Bump wheels to version 2023.10.0 (based on SDK release v1.2.0.0)
- Update device models to align with new specifications
> Bump Matter SDK to 1.2.0.0

- matter_server/common/helpers/util.py
closes https://github.com/home-assistant/core/issues/102863
> Add a cache to dataclass_from_dict

- pyproject.toml
Bump SDK wheels to version 2023.10.2 (SDK version 1.2.0.1)
> Bump sdk wheels to 2023.10.2

- matter_server/server/const.py
> Remove special character

- matter_server/server/device_controller.py
> Lower logging of attribute changed callback

- matter_server/server/device_controller.py
- make sure to only call resolve_node if really needed
- make sure that all paths return a value
> Fix some bugs in resolve node function

- matter_server/server/device_controller.py
A dual subscription to the same node appears to be more unstable than maintaining a single subscription with a maximum of 9 paths. Restore our code so we only handle one single sub per node instead of multiple, while keeping the other fixes we did lately.
Fixes #476 
Fixes https://github.com/home-assistant/core/issues/105480
> Restore single subscription to a node instead of dual

- matter_server/server/device_controller.py
Cancel any pending interviews when removing a node. Also log when a node gets removed.
> Cancel pending interviews when removing a node

- matter_server/client/client.py
The interview node command was still missing in the client
> Add interview node command to client

- matter_server/server/device_controller.py
Start counting at 1 and not zero
> Fix small typo in attempt count

- matter_server/client/client.py
- matter_server/client/models/node.py
Related frontend PR: 
https://github.com/home-assistant/frontend/pull/19692/files
> Add active fabric index to diagnostics

- matter_server/server/device_controller.py
We already track nodes going offline in the subscription logic, no need to also do it in the mdns listener logic as it will only cause false positives
> Ignore MDNS removal messages

- matter_server/client/client.py
- matter_server/server/device_controller.py
Fixes #577 
Adjusted the client to make it a non breaking change
> Uniform the result of read_attribute to always return a dict

- pyproject.toml
Changes see [v2024.2.2](https://github.com/home-assistant-libs/chip-wheels/releases/tag/2024.2.2)
> Update to Matter SDK wheels 2024.2.2

- matter_server/client/client.py
- matter_server/common/errors.py
- matter_server/common/helpers/api.py
- matter_server/common/models.py
- matter_server/server/client_handler.py
- matter_server/server/device_controller.py
- matter_server/server/server.py
- matter_server/server/storage.py
- pyproject.toml
> Fix deprecated imports

- matter_server/server/device_controller.py
The attribute update callback of subscription is called from the Matter SDK Thread directly. Most handling needs to run in the event loop Thread. Do a few quick checks, and then call the rest of the handler in the event loop Thread.
This also gets rid of a couple of `loop.create_task()` calls from the Matter SDK thread. `loop.create_task()` is not Thread safe.
> Make subscription attribute update handler Thread safe

- dashboard/src/pages/matter-node-view.ts
Adds a button to the dashboard to remove a node
> Add remove node support to the dashboard

- pyproject.toml
Changelog of [2024.3.2](https://github.com/home-assistant-libs/chip-wheels/releases/tag/2024.3.2).
> Update to Matter SDK wheels 2024.3.2

- matter_server/server/helpers/paa_certificates.py
On first attempt, we create the certificate directory. Because we use the directory as indication when the last fetch has been made, the directory modification timestamp is right now. This means that even if the fetching fails, subsequent Matter server startup would not retry fetching the credentials.
Make sure we retry in this case by clearing the modification timestamp
> Retry certification fetch if the first attempt fails

- matter_server/common/const.py
- matter_server/server/__main__.py
- matter_server/server/client_handler.py
- matter_server/server/device_controller.py
- Introduce extra log level: verbose
- Adjust some very verbose (and not daily useful) logs to verbose level
> Add verbose log level

- matter_server/client/models/device_types.py
- matter_server/server/device_controller.py
- pyproject.toml
- scripts/generate_devices.py
Bumps the wheels to version 2024.4 which is based on Matter SDK version 1.3
> Bump chip wheels to 2024.4.1 (Matter SDK 1.3)

- matter_server/server/device_controller.py
Fixes https://dpaste.org/HMF7U#L16
> Remove node from polled attributes when its removed

- matter_server/server/device_controller.py
- matter_server/server/server.py
Instead of checking self.server.loop in various places introduce a property to get the event loop.
> Introduce loop property to get the event loop

- matter_server/server/device_controller.py
Besides the existing cases, also listen for the BasicInformation Shutdown event. This is usually called when a node gracefully is being shutdown, e.g. after an update.
During testing, I've noticed that the Subscription callback closures capture the MatterNodeData object  in `_subscribe_node()`. This causes the callbacks to potentially update a stale version of the MatterNodeData objects, e.g. when trigger a re-interview: A re-interview doesn't cause the subscriptions to update, hence they still operate on the stale MatterNodeData object. Make sure to always get the MatterNodeData object in each callback closure.
> Fix and improve node unavailable handling

- dashboard/script/setup
- dashboard/src/client/models/descriptions.ts
Ensure that updates to the (custom) clusters and descriptions end up in the dashboard build.
- Update the definitions file now once
- Ensure the script to generate the descriptions runs at dashboard setup
This will also ensure that changes end up in the releases.
> Update dashboard definition files

- dashboard/src/pages/components/node-details.ts
- Fix update in progress button
- Add share button (open commissioning window)
> Debug UI: Fix update progres and add share button

- README.md
- scripts/setup.sh
Add a setup script to get the development config up and running with ease.
> Add setup script for development and adjust readme

- matter_server/common/custom_clusters.py
Add `ValvePosition` attribute of `EveCluster` Cluster for Eve Thermo.
> ValvePosition attribute of EveCluster Cluster

- dashboard/src/entrypoint/main.ts
Enhances production server recognition.
Fixes https://github.com/home-assistant-libs/python-matter-server/issues/913
> Add support for HACS hass_ingress integration

- dashboard/src/pages/matter-node-view.ts
Add device type(s) in node-view. It should fix this request: 
- #941
> Add device type(s) in node-view - Endpoint list

- DEVELOPMENT.md
Fixes https://github.com/home-assistant-libs/python-matter-server/issues/1075.
> Developer documentation: /data & IPv4 group limits

- dashboard/src/components/dialogs/acl/model.ts
- dashboard/src/components/dialogs/binding/model.ts
- dashboard/src/components/dialogs/binding/node-binding-dialog.ts
repair the binding delete failure problem, caused by error incoming parameters.
> fix matter binding detele error

- README.md
Updated README to announce the transition to matter.js and maintenance mode. To be merged when Matter server 8.1.1 got released
> Announce Matter Server rewrite and maintenance mode
