matter-js/python-matter-server

custom_components/matter_experimental/binary_sensor.py
custom_components/matter_experimental/entity.py
custom_components/matter_experimental/light.py
custom_components/matter_experimental/sensor.py
custom_components/matter_experimental/switch.py
matter_server/client/matter.py
matter_server/client/model/driver.py

Add logic to use the device type to decide what name to give the entity.

Create default better entity names

---

custom_components/matter_experimental/adapter.py

If the device doesn't have a device name, set a device name based on the first non-root device type.

Add a default device name based on device type

---

custom_components/matter_experimental/adapter.py
custom_components/matter_experimental/entity.py
custom_components/matter_experimental/services.yaml

- Update service descriptions
- Add a timeout when adding an entity in case the server cannot reach the device. Will mark device as unavailable if unreachable. We don't currently have a way to track if a device is back online, so requires a reload of the config entry.
- Fix adapter logging the correct device name when adding an entity

Timeout on add, service descriptions

---

custom_components/matter_experimental/entity.py

- NOT TESTED
- There was an extra entity state write done in the subscription callback flow. Remove that and make the entity attribute update method abstract.

Remove extra entity state write

---

custom_components/matter_experimental/adapter.py
custom_components/matter_experimental/entity.py
matter_server/client/model/node.py

Avoid multiple entites requesting reads and subscriptions of the same
node. Nodes seem to be overwhelmed and return a BUSY error code, which
isn't handled gracefully throughout the stack (it seems).

Synchronize attribute reads and subscriptions on startup

---

.github/workflows/test.yml
matter_server/client/model/device.py
scripts/chip_synchronize.py
scripts/list_unmapped_devices.py
scripts/show_stored_node.py
tests/fixtures/nodes/lighting-example-app.json

Add a script to parse a node dump or a matter_experimental custom integration storage file and print out all nodes and the entities they map to.
Added the output of the lighting example app as a fixture and run CI against it. This can be expanded to a lot more entities in the future.
```
❯ python3 -m scripts.show_stored_node tests/fixtures/nodes/lighting-example-app.json
<MatterNode 4337>
<MatterDevice DimmableLight (N:4337, E:1)>
- Platform: light
entity_cls: MatterLight
Subscriptions:
- OnOff.Attributes.OnOff
- LevelControl.Attributes.CurrentLevel
```

Add show_stored_node script

---

scripts/show_stored_node.py

The entity description is no longer printed as a dictionary on a single line.
```
<MatterDevice PressureSensor (N:4343, E:1)>
- Platform: sensor
entity_cls: MatterSensor
entity_description:
device_class: pressure
native_unit_of_measurement: kPa
measurement_to_ha: <function <lambda> at 0x10403e5e0>
subscriptions:
- PressureMeasurement.Attributes.MeasuredValue
```

Improve how entity description is printed

---

custom_components/matter_experimental/entity.py

Sometimes read/subscribe operations take longer (presumably mainly at
startup while searching for the node and establishing CASE sessions).
The stack has its own timeout handling as well, we should rely on those.

Do not timeout on subscribe/read operations

---

.github/workflows/test.yml
scripts/dump_fixer.py
scripts/show_stored_node.py
tests/test_utils/__init__.py
tests/test_utils/mock_matter.py

Extracted from #38
Sometimes we get a bad dump because the source is using a different version of Matter. This will propose changes to the dump to make the values work correctly in a test suite.
Our lighting-app fixture has one cluster that was [not processed correctly](https://github.com/home-assistant-libs/python-matter-server/blob/main/tests/fixtures/nodes/lighting-example-app.json#L247-L248). Running the script outputs can be used to update the fixture to represent real data:
```
❯ python3 -m scripts.dump_fixer tests/fixtures/nodes/lighting-example-app.json
Node 4337
** Found unprocessed cluster at endpoint 0: ThreadNetworkDiagnostics
Reason: Failed to decode field [].channel, expected type <class 'chip.tlv.uint'>, got <class 'chip.clusters.Attribute.ValueDecodeFailure'>
{ …
```

Add dump_fixer script

---

custom_components/matter_experimental/light.py
tests/fixtures/nodes/fake_color_temperature_light.json
tests/fixtures/nodes/fake_extended_color_light.json
tests/fixtures/nodes_in_ha/fake_color_temperature_light.json
tests/fixtures/nodes_in_ha/fake_extended_color_light.json

This allows toggling "Color Temperature Lights" and "Extended Color Lights". Color modes have not been implemented. Previously we wouldn't even show the lights.
Related to #19
Related to #20

Allow toggling advanced lights

---

custom_components/matter_experimental/__init__.py
custom_components/matter_experimental/binary_sensor.py
custom_components/matter_experimental/switch.py

Fix calling get cluster on wrong variable

---

custom_components/matter_experimental/__init__.py
custom_components/matter_experimental/services.yaml
matter_server/client/matter.py
matter_server/client/model/device_controller.py
matter_server/server/active_connection.py

This allows pairing an on network device using a new debug service `accept_shared_device`. To use this service you need a pin. This pin code can be received by opening a commissioning window for a device in another Matter controller.
The commission_on_network was originally added to the Python wrapper in https://github.com/project-chip/connectedhomeip/pull/21567
I didn't test this with an actual pairing code.
CC @jpelgrom

Allow pairing an on network device

---

matter_server/common/models/server_information.py
matter_server/server/device_controller.py
matter_server/server/server.py

devices can be commissioned while on the network, there is no hard requirement for the wifi creds.
Dropped the check and added a attribute instead so consumers can deal with it.

Drop requirement of WiFi credentials

---

matter_server/common/helpers/util.py

UnionType is not available on python3.9

Fix UnionType on Python3.9

---

.github/workflows/test.yml

- Split lint and test in two different jobs.
- The lint job should only run on the minimum Python version. The test job should run on all supported minor Python versions.
- Disable the test job for now, until the tests are fixed.

Split lint and test in CI

---

matter_server/server/device_controller.py
matter_server/server/server.py
pyproject.toml

With latest changes of the CHIP SDK the commissioning now works as intended and we can remove the workaround.
Note that this does not yet fix the attestation error for devices without valid certificate.
Depend on chip wheels 2022.12.0 (which is bumped in this PR)

Fix Commissioning

---

matter_server/server/device_controller.py

- Don't create a coroutine object prematurely.
- This solves an asyncio warning seen in unit tests.
```
tests/server/test_server.py::test_server_start
/usr/lib/python3.9/asyncio/base_events.py:673: RuntimeWarning: coroutine 'MatterDeviceController._check_interviews' was never awaited
self._scheduled.clear()
```

Avoid non awaited coroutine lingering

---

Dockerfile.dev

- Bump server to 1.0.8.
- Move paa-root-certs as done in add-on.
- Simplify chip installation.

Update docker image for server version 1.0.8

---

matter_server/server/device_controller.py
matter_server/server/server.py
matter_server/server/storage.py

`compressed_fabric_id` isn't set until the device controller is initialized, and we need the fabric id for loading from the storage path.

Fix persistency were controller failed loading commissioned devices

---

docker-compose.yml

Running in host mode is required for mDNS discovery which is needed when commissioning devices that are already on the network like the hue bridge.

Set network mode host and add default USERDIR in docker-compose.yml

---

matter_server/common/helpers/util.py
matter_server/common/models/device_types.py
pyproject.toml

Bump the SDK wheels to 2023.1.0 (built yesterday) which is based on official 1.0.0.2 patch release of the SDK

Bump SDK wheels to 2023.1.0 (=1.0.0.2)

---

matter_server/common/models/error.py
matter_server/server/device_controller.py
pyproject.toml

- Two commands had changed return value in chip SDK v1.0.0.2. This caused us to raise errors in the server when checking the return values for those commands.
- Fix that and let the exceptions that are raised by the chip stack bubble up to our handler instead.
- Bump version to 2.0.1.

Fix sdk command return code error handling

---

matter_server/common/models/node.py
matter_server/common/models/node_device.py

- `chip.clusters.Objects.Basic` was renamed to `chip.clusters.Objects.BasicInformation` in chip SDK v1.0.0.2.
- We didn't completely handle this in our version 2.0.0 release. Fix that now.
fixes #180

Fix device info and node BasicInformation

---

matter_server/client/client.py
matter_server/server/device_controller.py
tests/server/test_server.py

Adds support for sending extra arguments like `timedRequestTimeoutMs` to the matter server through the send_device_command function.
This doesn't change any of the previos arguments the function takes and there are defaults set for every extra argument so the HA core code doesn't need any modifications.
Resolve: https://github.com/home-assistant-libs/python-matter-server/issues/193

Add args support to send_device_command

---

matter_server/client/connection.py
matter_server/client/const.py
matter_server/common/const.py
matter_server/common/models/server_information.py
matter_server/server/const.py
matter_server/server/device_controller.py
matter_server/server/server.py

Make the schema version checks less strict so we have some more freedom of updating the addon/core independently.
- Remove strict check of sdk version alltogether. If there are any breaking changes, we can bump the schema version accordingly. NOTE to myself is to include the sdk version in the diagnostics when I'm reworking that.
- Use schema version constant (integer value) which we can bump if there are any breaking changes or new features.
- Define minimal supported schema version in the server itself, we should just keep things backwards compatible.
- Log warning if schema version does not match
- Keep logic in place to tie a feature to a schema version

Change schema version logic

---

Dockerfile.dev
README.md
compose.yml

Refactors/fixes the Docker version of the Python Matter server.
- Bumps base image to use official Python-provided Docker images
- Based on Debian Bulleyes
- Using Python 3.10
- Rename legacy `docker-compose.yml` to current default `compose.yml`
- Update readme to remove legacy commands; removed unneeded container reference in commands.
- Some small styling & typo squatting.
Tested and worked against the integration currently in the Home Assistant `dev` branch.
../Frenck
fixes #214

Refactor/fix Docker

---

matter_server/server/const.py
matter_server/server/device_controller.py
matter_server/server/helpers/paa_certificates.py
tests/server/test_server.py

- Address issues after https://github.com/home-assistant-libs/python-matter-server/pull/240.
- Move the certificates path constant to server constants. Use this constant directly in the helper script to fetch and generate certificates.
- Instantiate the chip controller when initializing the device controller instead of when instantiating the device controller.

Fix lint and test issues on main

---

matter_server/server/helpers/paa_certificates.py

This will add the required test VID certificates from the matter git but in the future, we should add a way to change this behavior from the UI, like that the end user can choose which certificates to allow.
Fixes https://github.com/home-assistant-libs/python-matter-server/issues/255

Add missing test VID certificates

---

Dockerfile.dev

To have a working docker build, `build-essential` package is required,
as psutils python modules is getting compiled and requires a gcc.

Fix Docker build, missing dependency

---

matter_server/server/device_controller.py

This change will make sure we always remove a node, even if it's offline or more importantly has been removed from our fabric by another controller or has been reset by the user.

Changed node removal behavior so fabric removal is optional

---

matter_server/server/device_controller.py

This will process node interviews and subscriptions asynchronously and block from running the task again until all queued nodes have been processed.
fixes: https://github.com/home-assistant-libs/python-matter-server/issues/265

Process nodes asynchronously

---

pyproject.toml

Bump the CHIP clusters wheel to 2023.4 this includes the patch for the "Schema not found" error we've seen with several devices that send custom attributes on the vendor specific cluster.
Fixes #270 
Fixes https://github.com/home-assistant/core/issues/88986

Bump chip clusters to 2023.4.0

---

matter_server/client/client.py
matter_server/common/const.py

No breaking changes but a new command was introduced: GET_VENDOR_NAMES hence the schema bump.

Bump API schema to version 3

---

matter_server/client/client.py
matter_server/server/vendor_info.py

Fixes issue that caused get vendor names to raise an exception if the vendor_filters parameter was used with a vendor missing from the DCL database like the NabuCasa and Amazon vendor IDs.

Fix get vendor names endpoint

---

matter_server/client/models/node.py

Fixes the name of the `DeviceTypeStruct` type variable from `type` to `deviceType` 
https://github.com/project-chip/connectedhomeip/blob/8f66f4215bc0708efc8cc73bda80620e67d8955f/src/controller/python/chip/clusters/Objects.py#L2764C19-L2776

Fixes variable that was renamed with sdk version 1.1.0.1

---

matter_server/client/models/node.py

Strictly speaking this may not happen, yet during testing with Switchbot devices I came across the edge case that one of the endpoints does not have a Descriptor cluster at all (completely missing).
Handle this in the code so we do not crash when this happens.

Handle edgecase where descriptor cluster is missing

---

Dockerfile.dev

Sync with changes made to addon dockerfile in https://github.com/home-assistant/addons/pull/3081
fixes #313

Update Dockerfile.dev - add dependencies for 3.5.0

---

.pre-commit-config.yaml
matter_server/client/models/device_types.py
matter_server/client/models/node.py
matter_server/server/device_controller.py
pyproject.toml
scripts/beautify_diagnostics.py
scripts/generate_devices.py

A bunch of small fixes I'd like to get in and release before merging the new features like climate and the refactored subscription logic.
- Fix devicetypes type hint
- Fix some typos 
- Add retry logic to resolving of nodes (might fix mdns resolve issues)

Some small bugfixes and stability improvements

---

.github/workflows/publish-to-pypi.yml
pyproject.toml

Use the tag created by the GitHub release and write it in the Python project metadata.
This is in preparation for Docker image build, which will rely on the release tag to fetch the latest Matter Server from PyPI.

Use release tag as project version when creating a release

---

matter_server/common/helpers/json.py
matter_server/common/helpers/util.py
matter_server/server/device_controller.py

Add a few safety guards when we receive unexpected data from the SDK.
This handles the case where one of the Attribute values is malformed, resulting in the complete node not able to serialize anymore which stalls the server completely even as the websocket api is no longer useable.
Skip (and log) those attributes.
Also clean up of some of the serialization code and remove redundant code.
Type conversions for serializing are now (only) done in the json encoder.

Fix crash on serialization error

---

.github/workflows/release.yml
Dockerfile
README.md
compose.yml

This adds a `Dockerfile` along with GitHub Action rules to build an official container image for the Python Matter server.
Fixes: #308

Build container image on Python Matter server release

---

matter_server/server/device_controller.py

Temporary patch that allows us to release a new matter server that is compatible with both HA 2023.7.x and below

Fallback to wildcard subscription if no explicit subscription defined

---

matter_server/client/client.py
matter_server/server/device_controller.py

Some small fixes/improvements based on feedback last couple of days:
- Require schema version 4 for the call to "subscribe_attribute"
- Rename "subscribe" to "subscribe_events" to make its purpose more clear [BREAKING]
- Raise NodeNotExists instead of KeyError in get_node method if the node does not exist

Some small fixes for the client

---

matter_server/client/client.py
matter_server/common/models.py
matter_server/server/device_controller.py

Add feature to write an attribute to a node

---

matter_server/client/client.py
matter_server/common/models.py
matter_server/server/device_controller.py

Add a command to read a live attribute value from a node
Usecase is a one-off read of some value (Like the thread diagnostics) where a subscription is not needed/wanted.

Add read attribute command/feature

---

compose.yml

Users are supposed to use the latest stable version of the container which is available under the tag "stable". The tag "latest" currently doesn't exist.

Use stable tag in example compose file

---

.github/release-drafter.yml
.github/workflows/pr-labels.yaml

Automatic version bumps to major, minor or patch based on the labels used within PR's.
@ludeeus @MartinHjelmare

Automatic versioning with release drafter

---

matter_server/server/device_controller.py

- Prevent concurrent resolve actions with a lock
- Simplify retry logic
- Retry more often
When one or more nodes are offline/unavailable (e.g. powered off, out of range, out of battery) at server startup, no automatic subscription is set-up for that device. Because the SDK does not expose a way to add a callback when a known node is discovered on mDNS, we do a regular poll to see if the device is back alive. This is now fixed and the poll interval is a little bit increased. It will start with a 30 second interval, slowly increasing that with 10 seconds to a maximum of 10 minutes, meaning that if one of those devices comes back online, it will take max 10 minutes for the server to pick the device back up again.
Once a device subscription has been set-up, a resubscription is done within a …

Improve node resolving for nodes offline at startup

---

matter_server/server/device_controller.py

Add a workaround that if a device is unavailable for a longer period of time (e.g. unplugged from power), we will fallback to regular polling (every 10 minutes) to detect if the device came back alive, just like we do with any devices that are offline when we startup the server.
By default we will use the resubscription logic within the SDK but if that resubsciption interval is higher then ours, we stop the subscription and create a job to poll this node on 10 minute intervals.
This is a workaround until the OperationalNodeDiscovery is implemented in the SDK, that way we can much more efficiently detect if a node is back online due to acting on the mdns packets.
Fixes #354

Add some workaround logic to poll devices that are unavailable for a longer period of time

---

matter_server/server/device_controller.py

Some small speedups and code cleanup

A few small optimizations

---

matter_server/server/device_controller.py

Handle a minor edge case where we keep retrying to interview an already deleted node.

Do not try to reinterview deleted node

---

scripts/generate_devices.py

Fix `gen_cls_name` function to generate the class name correctly even if `.` is in the device type name
I found `generate_devices.py` script has a bug when creating a class for a cluster corresponding to `PM2.5 Concentration Measurement` in `matter-devices.xml`. So, I modified the script code to ignore `.` in the device type name to sync with the connectedhomeip repository

Fix scripts/generate_devices.py scripts

---

pyproject.toml

Bump main branch to Matter SDK version 1.2 (RC1)
Did some basic testing this afternoon and everything still works as expected so no backward compatibility issues (so far).
1.2 specific changes/new features can be added once main is at 1.2
NOTE: For HA core we-re going to create a temporary branch while the exact release data of 1.2 is not in sync with the HA release cycle.

Bump chip wheels to 2023.11.0b1 (sdk 1.2 rc1)

---

README.md
matter_server/client/client.py
matter_server/server/device_controller.py

commission_on_network has a very confusing name and is actually not used for commissioning. I left it in the public api to not break anything but I've updated the docstrings and readme. commission_with_code is used for all scenarios, even for on-network devices like bridges and sharing from another controller. This was not very clear at this point.
fixes #408

Cleanup/clarify commission_on_network

---

matter_server/server/device_controller.py

Adjust our subscription logic a bit based on the recent discussions around this topic within CSA where a too low subscription ceiling hurts (thread) networks and battery life. 
- Adjusted our report interval ceiling to a random interval between 500 and 700 seconds, so more or less 10 minutes
- Removed the manual resolve workaround as it was too noisy, let's wait for the real solution where operational nodes are rediscovered
- Updated comments to explain the situation
- Switch to wildcard subscriptions as soon as the amount of watched attributes is above 9

Adjust subscription logic a bit

---

matter_server/server/device_controller.py

Instead of re-interviewing every 30 days, just check the software version number of a node.
If the software version changed, schedule a re-interview.

Automatically re-interview a node if its software version has changed

---

Dockerfile

To help diagnose connectivity issues we intend to add diagnostics functionality. We plan to use regular IP utilities for this, hence add them to the base container. They might also be helpful when manually debugging connectivity issues.

Add IP utilities for diagnostics

---

matter_server/server/device_controller.py

While diagnosing the infinite loop issue reported in #426 (and on discord as well) I figured we can remove this workaround for now. I don't think it's actually the cause of the issue but maybe inducing it. There is no more real need for it anyway now that we've lowered the subscription ceiling.

Remove the workaround that is overriding the liveness timeout

---

matter_server/common/models.py
matter_server/server/device_controller.py

We've got reports about an infinite loop in the sdk resubscription logic where the resubscription is attempted without respecting the timeout, causing an endless loop consuming a full cpu core.
Awaiting further investigation I have now put in a quick guard in the code that detects the infinite loop, logs it as error and tears down the subscription. The reconnect is then handled by our poll logic.
Closes #426

Add temporary guard for infinite loop in resub logic

---

matter_server/server/device_controller.py

Debounce marking a node as unavailable a bit to ignore very quick reconnects (which are unavoidable in an IP based network). If a node is unavailable for 10 seconds or more, the node will be marked as unavailable. This is comperable to how other controllers (such as Apple Home, Google Home) do this so the experience will be more alike.

Debounce node availability a bit

---

matter_server/client/client.py
matter_server/client/models/clusters.py
matter_server/client/models/node.py
matter_server/common/const.py
matter_server/common/helpers/json.py
matter_server/common/helpers/util.py
matter_server/common/models.py
matter_server/server/const.py
matter_server/server/device_controller.py

- Support reading custom Clusters and Attributes
- Skip overhead by using raw tlv values in the server
- Add custom models for Eve custom cluster (for energy plug readings)
- Refactor serialization; now that we use the raw values we can let orjson deal with serializing - this means speed improvements
We're now sending the raw tlv values from the read requests in the server to the client so we skip the overhead of having to go through the models. This allows us to see all values, so including the custom attributes for which there are no models defines in the SDK wrapper. Also, skipping the intermediate step gives us a speed bump.
**SCHEMA CHANGED TO VERSION 5**
Although there are no breaking changes in any of the public methods, the data schema is not compatible and has been bumped to …

Support custom Clusters and Attributes

---

pyproject.toml

- Latest aiohttp now only includes async-timeout if running on Python 3.10 or lower.
- Include async-timeout explicitly for now until we bump minimum Python version. Python 3.11 has `asyncio.timeout`.

Add async-timeout

---

README.md
matter_server/server/device_controller.py

Strictly taken this should not be needed but we've seen that thread networks can suffer from interference and/or discovery failing for some devices. This increases the chances that the commissioning of a node succeeds by simply retrying the resolving with extended timeouts.

Implement more aggressive retry logic for resolving and first interview

---

matter_server/server/device_controller.py

TypeError: cannot unpack non-iterable CommissioningParameters object
python3 --version Python 3.10.12
Suspected Reason:
open_commissioning_window in device_controller.py calls _call_sdk(self.chip_controller.OpenCommissioningWindow) which returns 3 values not 2 (pin, code, qrcode) 
Steps to reproduce:
1) flash latest esp32 lighting-app example to ESP32 dev kit
2) set the wifi credentials on the python-matter-server
{"message_id": "1","command": "set_wifi_credentials","args": {"ssid": "MYSSID","credentials": "MYPASS"}}
3) commission with code (for esp32 lighting-app)
{ "message_id": "2","command": "commission_with_code","args": {"code": "34970112332"}}
4) Once commissioning is successful as node 1, try to open a commissioning window:
{"message_id": "5", "command": …

Fix open commissioning window tuple bug

---

matter_server/server/device_controller.py

our resolve_node helper is only used for operational node discovery so it makes no sense to even try a PASE session (as that is only used for commissionable nodes).
Some users have reported a crashing matter server - this seems to be true only for those who have unreachable devices, hence our retry logic kicks in. This may be the cause (or at least it does not hurt to try)

Disable PASE for operational node discovery

---

matter_server/client/client.py
matter_server/server/device_controller.py
pyproject.toml
tests/server/test_server.py

Add a parameter which instructs the SDK to search for the device only on the network. This is useful when using the manual pairing code, which does not contain a device specific discovery capabilties.
This is useful to prevent the SDK from searching via Bluetooth from the Android App (which provides a manual pairing code when using the non-App integrated Matter onboarding flow).

Allow to commission with code on network only

---

matter_server/common/models.py
matter_server/server/__main__.py
matter_server/server/device_controller.py

A bunch of (small) optimizations in the commissioning and (re)subscription flows again based on some investigation with various devices. 
- Remove fetching certificates before commissioning (as it only slows down and doesn't do anything)
- Ignore failed commissioned nodes at startup
- Cancel subscription at node removal
- Speed up resolve
- Split up node attribute subscriptions into 2 subscriptions
- Lower the ceiling once again
- Adjust logging of PersistentStorage module of sdk because it was too chatty

Optimize commission and (re)subscription flows

---

matter_server/server/device_controller.py

Prevent lingering task errors on early shutdown by moving the scheduled interview to its own function.

Move delayed interview to own callback

---

matter_server/client/client.py
matter_server/common/const.py

- Bump schema to version 6
- Require schema version 6 if trying to use the new network_only param
The schema is backwards compatible so not a breaking change

Bump schema version to 6

---

matter_server/server/device_controller.py

Fix regression where the last used NodeID is not stored so causing a collission and effectively preventing multiple commission actions. Store the Node ID we tried at all times. Other logic will make sure that we only start interviewing existing nodes.
Fixes #482

Immediately store last used node id

---

matter_server/server/device_controller.py

We still had a lock (just in case) for resolving nodes. In the meanwhile we learned that its not resolving but subsequent actions on a node that needs to be guarded/locked. With the latest refactor to do all node resolving in the "_resolve_node" helper function this lock was used when not needed. So for example when the server is attempting to resolve unreachable nodes, all (server wide) node actions would then be blocked.
Removing the lock fixes this useless waiting resulting in a massive speedup as well as bugfix for the unstable subscription (continuous resubscriptions)
I have stress tested to ensure that this lock is really no longer needed. I did not experience a segfault.
We do need to keep an eye on using the node_lock at all times because that can in fact induce a segfault due to …

Remove (pointless) resolve lock

---

matter_server/server/storage.py

When two save tasks are scheduled, they might race and cause exceptions as follows:
```
2024-01-04 11:33:06 core-matter-server asyncio[245] ERROR Task exception was never retrieved
future: <Task finished name='Task-192' coro=<StorageController.async_save() done, defined at /usr/local/lib/python3.11/site-packages/matter_server/server/storage.py:143> exception=FileNotFoundError(2, 'No such file or directory')>
Traceback (most recent call last):
File "/usr/local/lib/python3.11/site-packages/matter_server/server/storage.py", line 159, in async_save
await self.server.loop.run_in_executor(None, do_save)
File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
result = self.fn(*self.args, **self.kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File …
```

Use lock to avoid concurrent save tasks

---

matter_server/server/device_controller.py

alternative to #448 
validated locally:
```json
{
"message_id": "c9627ca8-b91d-4f76-98de-91d4f34cd495",
"result": [
{
"instanceName": "<redacted>",
"hostName": "<redacted>",
"port": <redacted>,
"longDiscriminator": <redacted>,
"vendorId": 4874,
"productId": 89,
"commissioningMode": 2,
"deviceType": 263,
"deviceName": "Eve Motion",
"pairingInstruction": "",
"pairingHint": <redacted>,
"mrpRetryIntervalIdle": 3300,
"mrpRetryIntervalActive": 1100,
"supportsTcp": false,
"addresses": [
"<redacted>"
],
"rotatingId": "<redacted>"
}
]
}
```

Fix json serialization for discovery api

---

matter_server/server/vendor_info.py

this api defaults to a limit of 100 vendors. adds a loop to fetch all the pages
docs: https://on.dcl.csa-iot.org/#/Query/VendorInfoAll
logs after update
```
2024-01-05 02:28:11 3bf053e85e29 matter_server.server.vendor_info[1] INFO Loading vendor info from storage.
2024-01-05 02:28:11 3bf053e85e29 matter_server.server.vendor_info[1] INFO Loaded 0 vendors from storage.
2024-01-05 02:28:11 3bf053e85e29 matter_server.server.vendor_info[1] INFO Fetching the latest vendor info from DCL.
2024-01-05 02:28:12 3bf053e85e29 matter_server.server.vendor_info[1] INFO Fetched 142 vendors from DCL.
2024-01-05 02:28:12 3bf053e85e29 matter_server.server.vendor_info[1] INFO Saving vendor info to storage.
```

Add pagination for vendors query

---

matter_server/server/client_handler.py

In case we encounter an unhandled ChipStackError during processing a websocket message, make sure we note that in our server logs as well.
Typically we should handle those errors and convert them to Python Matter server specific errors.

Log ChipStackError as well

---

matter_server/server/__main__.py
matter_server/server/device_controller.py
matter_server/server/server.py
pyproject.toml
tests/server/test_server.py

Scope link-local IPv6 addresses received from WebSocket
When receiving link-local IPv6 addresses, remove the scope by default
as the scope id is typically from a remote machine (e.g. from the Android
phone).
If the Matter server got started with a primary interface set, scope the
link-local address to that interface instead.
This fixes commissioning issue for WiFi devices when using the Android
in-app commissioning flow which sends the IP address of the device
to be commissioned alongside.
Related-to: #463

Scope link-local IPv6 addresses received from WebSocket

---

matter_server/server/device_controller.py

Ideally, we like to remove the Home Assistant fabric from a device. We optimistically execute the command to remove the device.
Check the result of the device removal and print a message accordingly so users can tell if removing was successful.

Print result of device removal

---

matter_server/server/device_controller.py

There was a small oversight in the recently added code to log the success of a node removal.

Fix Node removal

---

matter_server/client/client.py
matter_server/client/models/node.py
matter_server/common/helpers/util.py
matter_server/common/models.py
matter_server/server/device_controller.py
matter_server/server/helpers/utils.py
matter_server/server/vendor_info.py
tests/common/test_utils.py
tests/server/test_utils.py

Add models and functions to get (and refresh) diagnostic details for Matter nodes:
- Add ping_node command to the server to refresh and ping all ip addresses of a node and return them in a human readable format.
- Adjust matter_fabrics helper in the client to refresh the data
- Add node_diagnostics helper in the client to return a collection of node diagnostics in a human readable format, already prepared in a custom format that is more ready suitable for HA (like string enums that can be used as translation keys)

Add diagnostics for matter nodes

---

matter_server/server/device_controller.py
scripts/example.py

- ignore attribute updated callback if value did not change
- fix save changed node info to persistent storage
- cleanup of orphaned nodes
- fix example script
closes #496

Improvements and bugfixes for persistent storage of node data

---

matter_server/server/device_controller.py

It's still not entirely clear but it looks like multiple resolves at the same time is not very safe and one action may even be discarded if another attempt comes in. So for example if the server is busy trying to resolve an offline node it may cause commissioning to fail. So for safety reasons put a lock on the resolving. It makes init of nodes somewhat slower but its safer.

Guard node resolving with a lock

---

matter_server/client/client.py
matter_server/common/models.py
matter_server/server/device_controller.py

The server returns a CommissioningParameters object on the "open_commissioning_window" which is a dataclass specified in the chip devicecontroller.
The typing on our python client side was still a tuple, so wrong.
Copied the CommissioningParameters dataclass to our shared models for the client.

Fix model for CommissioningParameters in client

---

matter_server/client/client.py
matter_server/client/models/node.py
matter_server/server/device_controller.py
matter_server/server/helpers/utils.py

After playing a bit with the diagnostics fetching while implementing it in the frontend, I quickly came to the conclusion that it was not working as intended, especially the retrieval of the values and ping slows it down badly, especially for thread devices. So some changes;
- Add IP addresses and fabrics to watched attributes (so we do not have to fetch them)
- Remove ping from diagnostics 
- Use available bool on diagnostics model
- no duplicate conversion needed for network name

Speedup diagnostics

---

matter_server/server/stack.py

When shutting down the Certificate Authority Manager, the underlying code needs the chip stack to properly free up all resources. Manually shutdown the Certificate Authority Manager to avoid exception later during shutdown.
This avoids stack traces as follows:
```
Exception ignored in: <function CertificateAuthorityManager.__del__ at 0x7d523bd51260>
Traceback (most recent call last):
File "/home/sag/projects/project-chip/python-matter-server/venv/lib/python3.11/site-packages/chip/CertificateAuthority.py", line 306, in __del__
self.Shutdown()
File "/home/sag/projects/project-chip/python-matter-server/venv/lib/python3.11/site-packages/chip/CertificateAuthority.py", line 296, in Shutdown
ca.Shutdown()
File "/home/sag/projects/project-chip/python-matter-server/venv/lib/python3.11/site-packages …
```

Shutdown Certificate Authority Manager before the stack

---

matter_server/server/__main__.py
matter_server/server/helpers/custom_web_runner.py
matter_server/server/server.py
tests/server/test_server.py

Allow to define which IP addresses to bind the WebSocket server on. This is especially useful to limit which addresses the add-on will listen on since it runs in host network context.

Support specifying which IP addresses to listen on

---

matter_server/client/connection.py
matter_server/server/client_handler.py

Log non-text messages in websocket api
Addresses #523

Log non-text messages in websocket api

---

matter_server/server/device_controller.py
pyproject.toml

Implemented zeroconf to do our own mdns discovery of operational (and later commissionable) Matter nodes.
This solves a number of issues, most importantly that we do no longer have to rely on the (bad) polling behavior of the SDK if a node goes unavailable. Instead we can detect it coming back online through mdns discovery proactively.
- Initialize nodes on discovery over mdns
- Do no longer try to resolve all nodes at startup (as only the live ones will be discovered over mdns now).
- Mark node offline if zeroconf reports it as offline.
- Prepare listening for commissionable nodes, to be picked up in a follow-up PR.
- Some small polishes such as deny commands to an unavailable node
Fixes:
- Continuous error logging of the SDK trying to resolve offline nodes.
- If a Matter device is …

Implement zeroconf for operational node discovery

---

matter_server/server/device_controller.py

Handles bit of an edge case but still....
Allows removing of a node for which we have no attribute data at all.

Fix for removal of orphaned node

---

matter_server/server/device_controller.py

Just as a safe guard, treat mdns update events as add events just to catch the edge case where we somehow missed the add message.

Treat mdns update events as add events as safeguard

---

matter_server/server/device_controller.py

Adjust the processing of mdns events for operational matter nodes a small bit.
We want to process them in sequential order but at the same time not block processing if one node is just slow to respond or whatever.
This introduces a queue and queue processing task per node (or strictly speaking, mdns name)

Process the mdns messages semi parallel

---

matter_server/server/const.py
matter_server/server/device_controller.py

A full re-interview was required when the API schema was bumped, which was not correct.
We only need to force a re-interview when the node data changed, for example when we bumped the sdk or changed the datamodel.
Also a bit of polishing of the interview logic itself.

Refactor the interview logic a small bit

---

matter_server/common/helpers/util.py
matter_server/server/device_controller.py

Always try to instantiate a MatterNodeData object from the cache info and if that fails, fallback to a default object.
Let the interview logic sort out if a re interview is really needed

Prevent duplicate interviews

---

matter_server/server/device_controller.py

Kind of a stupid mistake... The fabric hex can start with a leading zero

Fix for leading zero mismatch in fabric check

---

dashboard/.gitignore
dashboard/README.md
dashboard/package-lock.json
dashboard/package.json
dashboard/public/index.html
dashboard/rollup.config.mjs
dashboard/script/build
dashboard/script/develop
dashboard/script/setup
dashboard/src/client/client.ts
dashboard/src/client/connection.ts
dashboard/src/client/exceptions.ts
dashboard/src/client/models/model.ts
dashboard/src/client/models/node.ts
dashboard/src/components/dialog-box/dialog-box.ts
dashboard/src/components/dialog-box/show-dialog-box.ts
dashboard/src/components/ha-svg-icon.ts
dashboard/src/entrypoint/main.ts
dashboard/src/pages/matter-dashboard-app.ts
dashboard/src/pages/matter-dashboard.ts
dashboard/src/pages/matter-node-view.ts
dashboard/src/pages/matter-server-view.ts
dashboard/src/util/fire_event.ts
dashboard/src/util/prevent_default.ts
dashboard/src/util/routing.ts
dashboard/tsconfig.json
matter_server/client/connection.py

Add a basic dashboard for development. Based on [the work](https://github.com/wozz/matter-server-ui/tree/main) by @wozz. The client/connection classes are mimicked from their Python counterparts.

Add an initial basic dashboard

---

matter_server/server/__main__.py
matter_server/server/device_controller.py
matter_server/server/stack.py
pyproject.toml

Use the Matter SDK's log filtering capability. This avoids unnecessary calls into the Python library. Also introduce custom Python logging levels for the SDK log entries to make them distinct. This helps to easier spot SDK messages and match them to the log category semantics used in the SDK.
Note that there are two log entries shown on stdout right when initializing the logging, specifically:
```
[1708008135.838346][77288:77288] CHIP:CTL: Setting attestation nonce to random value
[1708008135.838417][77288:77288] CHIP:CTL: Setting CSR nonce to random value
```
These are messages which are printed when the native library gets loaded the first time (constructors of globals). We can't install the Python redirect. So these messages are printed using the native libraries default logger, which …

Filter Matter SDK logging in SDK

---

pyproject.toml

Address a few small improvements to the linter config, as discussed in #548
- Disable Ruff TCH001 and TCH003 (requirement to move imports into type checking block)
- Disable ruff rule EM102 (disallow f strings in log)

A few small improvements to the linter config

---

matter_server/server/device_controller.py

After our recent change with the proactive node detection using our own mdns discovery we also changed how/when we mark a node as unavailable/offline if its not responding. we lowered the treshold in favor of re-detecting it over mdns.
We however get multiple reports that people now see their nodes go unavailable a lot more often.
Now we can go argue that they should fix their networks/devices so they do not miss the subscription intervals but real world is that dropouts may happen and bad devices do exist ;-)
I have investigated other platforms like Apple Home and Google home and they're all a huge bit more forgiving than us, basically "hiding" the node unavailability for a while by debouncing it. This PR extends our tresholds as well to follow that pattern but it still logs these events …

Delay marking a node as unavailable

---

.github/workflows/test.yml

Our test workflow should ignore the pre-commit action for push to main if running from CI (but still run locally)

Skip push to main branch check in test workflow push

---

.github/workflows/release.yml

The release action fails 6 out of 10 times due to a race condition.
The new version is published to PyPI but then the container build action requires that same PyPI package and often fails to resolve it because its not yet visible in the indexer.
This puts a 1 minute sleep between the 2 actions to hopefully resolve this.

Delay building of the container after publishing to PyPi

---

.github/workflows/release.yml

Turns out 60 seconds was still too short, extended it to 120 seconds.
Let's see next time if it succeeds.

Extend sleep in release action

---

matter_server/server/device_controller.py

It turns out that a single wildcard subscription is friendlier for devices than specific path subscriptions due to memory constrains

Switch (back) to a single wildcard subscription per node

---

matter_server/server/device_controller.py

- debounce incoming mdns events (as they arrive in bursts, especially when a node is restarting)
- always handle a ADDED event (as that arrives when a node restarts)
- ignore update events if the node is known to be still alive
- simplify the code by removing the overcomplex queue logic
Tested this for a while with both powered and battery powered nodes and its working great.
Its especially a huge improvement for rediscovering battery powered nodes.

Some improvements to the operational node discovery using mdns

---

matter_server/server/device_controller.py

Temporary change the log level of this deprecated command warning because otherwise people running HA will think something is wrong. Change it back once we released a HA version that is modified to no longer send this command.

Change log level of deprecated subscribe attribute

---

matter_server/server/device_controller.py

There's no lock needed for resolving nodes. This is a a leftover from previous test attempts.
The only important lock is the node lock, to only do one concurrent action towards a node.
Removing this lock will also significantly speedup initial setup as there is no more useless waiting involved.

Remove resolve lock

---

matter_server/client/client.py
matter_server/common/const.py
matter_server/common/models.py
matter_server/server/device_controller.py

Now that we have zeroconf in our server we can do a better job to get the known ip addresses.
This change makes sure that we fetch the (scoped) ip addresses by querying mdns and return cached info if the node is offline.
Also updated the node diagnostics in the client to use this new method of fetching the ip's if the server schema version matches, will fallback to the old method otherwise.
schema bumped to version 8 due to the new command but no breaking changes.

Fix ping node and retrieval of IP addresses

---

matter_server/common/helpers/util.py
matter_server/server/device_controller.py
matter_server/server/helpers/attributes.py

Writing attributes values with JSON data is allowed in Matter, for instance with the ACL cluster we can send this payload:
<details>
<summary>Expand</summary>
```
[
{
"fabricIndex":0,
"privilege":5,
"authMode":2,
"subjects":[
112233
],
"targets":null
},
{
"fabricIndex":0,
"privilege":1,
"authMode":2,
"subjects":[
4444,
5555,
6666
],
"targets":null
},
{
"fabricIndex":0,
"privilege":3,
"authMode":3,
"subjects":[
123,
456
],
"targets":[
{
"cluster":6,
"endpoint":null,
"deviceType":null
},
{
"cluster":null,
"endpoint":1,
"deviceType":null
},
{
"cluster":8,
"endpoint":2,
"deviceType":null
}
]
}
]
```
</details>
When Python parses this JSON, the `null` value is then converted to a Python `None`. This `None` is not allowed by the Matter SDK, at the opposite of the `Nullable` type which is …

Fix Nullable values in write attributes procedure

---

matter_server/server/__main__.py

(temporary) raise the log level of zeroconf as its a logs an annoying warning at startup while trying to bind to a loopback IPv6 interface

Lower log level of zeroconf

---

matter_server/server/device_controller.py

If a device has been put into commissioning mode and you issue the command again (e.g. by pressing the button in the HA interface) the device will throw a (rather cryptic) message because its already in commissioning mode.
Fix this by returning the previous parameters (and clear them once the timeout expires)
Closes https://github.com/home-assistant/core/issues/109936
Another improvement is creating a random discriminator instead of a hardcoded one.
Also, add a check if the node is actually available (so a case session is active) before attempting to open the commissioning window, which should prevent #558

A few small fixes to the share (open commissioning window) feature

---

matter_server/server/helpers/paa_certificates.py

Some users had reported that their Matter server didn't start and [while inspecting their logs](https://github.com/home-assistant/core/issues/111251#issuecomment-1966840622) I noticed the fetching of certificates from Github was raising a TimeoutError we weren't catching.
Still, not retrieving the certificates can cause issues when trying to commission new nodes but a not starting Matter server isn't very nice either.
NOTE: It's not possible to load these certificates while running. They must be fetched before starting the devicecontroller.

Catch TimeoutError while retrieving certificates

---

.github/workflows/release.yml
dashboard/src/entrypoint/main.ts
dashboard/src/pages/matter-dashboard.ts
matter_server/server/server.py
pyproject.toml
tests/server/test_server.py

- Build the dashboard in the release script
- Host the dashboard on the builtin webserver
- Detect the production server based on our default port
This is just the base dashboard as-is with no added functionality, that is to be extended in follow-up PR's.

Include (base) dashboard in the builtin-webserver

---

.github/workflows/release.yml
.gitignore
dashboard/README.md
dashboard/script/build
matter_server/server/server.py
pyproject.toml

After publishing 5.7.0 beta 0 I found out that the (prebuilt) dashboard wasn't included in the python wheel.
Modified the build script a bit to build the frontend into a dashboard subfolder of the matter_server, which will then recursively be picked up by setuptools.

Ensure that the dashboard build is included in the py wheel

---

Dockerfile
Dockerfile.dev
pyproject.toml

With Matter SDK wheels 2024.2.1 OpenSSL is no longer required as statically linked BoringSSL is used.
This also gets rid of the mDNS failed to join multicast group errors on startup.

Update to Matter SDK wheels 2024.2.1

---

matter_server/server/device_controller.py

Using multiple worker Thread when calling the SDK doesn't really add any benefit: The Python wrapper posts all SDK calls onto a single Thread anyways (see ChipStack.py:Call()). Instead, use a single Thread to call the Python wrapper.
This potentially avoids race condition in the Python wrapper.

Use single SDK worker Thread

---

matter_server/server/__main__.py
matter_server/server/client_handler.py
matter_server/server/device_controller.py
matter_server/server/server.py

After testing the 5.7.0 beta we collected a few tweaks to stabilize and enhance the server, especially for larger devices.
One important fix was to limit access to the SDK to a single thread with a single thread executorpool (already merged in separate PR). We also discovered that we were not catching unhandled exceptions.
This branch had a number of iterations while testing on users but in the end this is what's left;
- Enhance the logging config with some common tweaks such as showing the thread.
- Catch all unhandled exceptions in threads and asyncio tasks.
- Only print full stacktraces for exceptions if debug logging is enabled, otherwise just log a pretty-fied version.
- A few small tweaks to the mdns discovery and subscription ceilings

A collection of small (stability) fixes and tweaks

---

matter_server/server/device_controller.py
matter_server/server/helpers/utils.py

Some nodes are just super slow to respond or the network may be busy.
Do multiple ping attempts when we discover a node on mdns.

Do multiple ping attempts when discovering a node

---

matter_server/server/device_controller.py

While skimming through user logs I noticed that sometimes a call to the sdk (especially the read attribute one) seems to be hanging forever. I think its good for detection and deadlock-preventing to add timeouts to the sdk calls.
I've set the default to 5 minutes per call. Now with a single executor thread handling all calls to the SDK that seems reasonable. If calls take (even) longer than 5 minutes to complete, something is seriously wrong.

Add timeouts to sdk calls and subscription set-up

---

matter_server/server/device_controller.py

While we're figuring out the weird edge case with mdns discovery that causes some messages to be missed, this adds a fallback scanner to pickup nodes that are operational but not picked up by mdns. It runs every 30 minutes

Add fallback scanner for Matter nodes

---

matter_server/server/device_controller.py

It turns out that TimeOutError does not have a nice printable presentation so use the class name in case this happen (to any of the exceptions we like printed)

Add fallback log name for exceptions

---

matter_server/server/device_controller.py

Remove locking and timeout handling for now

Refactor locking and timeout to sdk access

---

matter_server/server/stack.py

Make sure to initialize logging after the native code init. This makes sure that the C++ pychip_native_init is called after pychip_CommonStackInit. This is required to make sure that the platform specific initialization in src/platform/Linux/PlatformManagerImpl.cpp is being called before using the SDK.
See also: https://github.com/project-chip/connectedhomeip/pull/20234

Initialize logging after native init

---

matter_server/server/stack.py

Make sure the SDK log level is being set according to the Matter server command line arguments or their default.

Fix setting SDK log level on startup

---

matter_server/server/device_controller.py
matter_server/server/helpers/utils.py
matter_server/server/server.py

- Remove Timeout (as it is no longer needed now we identified the source)
- Allow cached ip in background scanner
- Use SDK resolve in node setup instead of zeroconf/ping
- Allow running the loop in debug mode on dev setup
- fix interview_node
- handle race condition in ping
- better debouncing of mdns

Several improvements to resolving and (re)subscribing to nodes

---

matter_server/server/client_handler.py

- Pretty log handled exceptions (with node id if possible)
- Print full stack traces for unhandled exceptions by re-raising it after informing the client

Better logging of client errors

---

matter_server/server/device_controller.py

While bug hunting we suspected that the the C-Types wrapper to the SDK may not be completely thread safe so we added a limit on the asyncio executor to limit it to a single thread. Now that we have more insight in the lockup bug, it does not seem to be the cause and inspecting the code reveals that the code is pretty thread safe actually...
As I read it now everything is already thread safe as every action is posted as job to the sdk with the chipStack.Call or chipStack.CallAsync and then the result is returned when the job has been executed by the sdk, which will schedule the work on its own threads.
Now that we have limited the executor to a single executor, we're blocking concurrent actions.
For example if we're busy resolving a node, we cant execute any device commands at the same …

Remove executor limit

---

matter_server/server/__main__.py
matter_server/server/const.py
matter_server/server/device_controller.py
matter_server/server/helpers/paa_certificates.py
matter_server/server/server.py

Add a new server argument --paa-root-cert-dir to allow a custom location for PAA root certificates. This allows to store them in a location which is preserved.

Add server argument to specify custom PAA root certificate location

---

matter_server/server/device_controller.py

Last couple of weeks we have been investigating some sdk lockup issues. In fact it's not a complete deadlock but a node setup (initial read subscription) that takes forever. In our observations the transmission is halfway aborted in the read request and then resumed in some sort of loop, so the Read request never finishes.
It's hard to reproduce the issue and if its limited to only Nanoleaf bulbs or also other devices and if the type of Border routers make a difference. 
This PR adds a big fat warning in the log if we detect this situation if the node setup takes longer than 15 minutes.
It will keep logging this message every 15 minutes until the user takes action. There are only 5 slots available for node setup so if all 5 are taken, the server will stall setting up any new nodes.
The …

Add warning if node setup takes too long

---

matter_server/server/__main__.py

This can be useful during debugging and performance comparison and aligns with what Home Assistant Core is using.

Use milliseconds in log time stamp

---

dashboard/src/entrypoint/main.ts

Swap the check around so we assume a production server when we don't detect the dev server port.
This is (still) just a simple approach without actually connecting if there's a server alive. Good enough for now.

Allow the dashboard to be hosted in ingress

---

matter_server/server/device_controller.py

Make use of the newly added async friendly GetConnectedDevice so we can skip the executor

Use async resolve node

---

matter_server/server/device_controller.py

We changed our datamodel a while ago and we only store the raw node attributes now so we don't have to deal with the custom dataclasses at all serverside. The MatterNode object is a basic dataclass that is perfectly serializable by orjson directly. Skip the unneeded dataclass_to dict to store the MatterNode object to persistent storage.
supersedes https://github.com/home-assistant-libs/python-matter-server/pull/653

Skip unneeded dataclass conversion in storage

---

pyproject.toml

It seems unused, so let's drop it.

Drop Python safety module from dependencies

---

matter_server/client/client.py
matter_server/server/device_controller.py

While we're still hunting down the cause for the continuous "subscription failed with Error: 50, re-subscribing in 0 ms" errors where the subscription of a node suddenly gets lost with no reason, I found a few tweaks. Not really solutions to the issue but still good to apply.
- Increase subscription ceiling for WiFi devices to 60 seconds (same as mains powered thread devices) as we see the error mostly for WiFi devices.
- Remove keepSubscriptions on the subscription itself as its kind of redundant with the autoResubscribe and saves a bit of stress on the device itself (hopefully) - though this is still very unclear.
- Remove fabricFiltered=False (so reinstate it being set to True) on the subscription itself as the only reason we were doing that is to have an up to date list of fabrics at …

Some small tweaks to the subscripions logic

---

matter_server/common/helpers/util.py
tests/common/test_parser.py

Somehow some devices send some values (such as the Noc) as integer instead of bytes so our parser chokes on that.
Not sure if this is device related or somehow the tlv parser doesnt handle it but its not super big deal.
Convert it so parsing the values doesnt crash in the client.
Fixes https://github.com/home-assistant/core/issues/116304
Fixes https://github.com/home-assistant/core/issues/113279

Handle value specified as bytes received as integer

---

matter_server/server/helpers/paa_certificates.py

Matter PAA certificates must have X509 Subject Key Identifier extension. The current code already deduplicated the certificates from the DCL based on this identifier.
This rewrites the code such that certificates fetched from git are deduplicated as well.

Deduplicate PAA certificates using Subject Key Identifier

---

matter_server/server/helpers/utils.py

On Linux, the ping binary can be used for IPv4 or IPv6. In fact, on distributions which have ping6 it is just a symlink to ping. But not all Distributions seem to have the symlink. So rather use the regular ping binary and explicitly specify the IP version.

Use ping binary for IPv6

---

matter_server/common/models.py
matter_server/server/stack.py

It seems that the linter changes introduced in #687 broke some imports necessary at runtime. Make sure both, runtime and linter are happy.

Fix imports at runtime

---

matter_server/server/device_controller.py

We request a certain report interval, but some devices (especially ICD SIT, Intermittently Connected Devices with Short Idle Time) may report with a higher ceiling because these devices might want to sleep for longer. Logging this information can be helpful to debug issues with such deviecs.

Log effective reporting interval

---

pyproject.toml

Matter SDK/CHIP wheels [2024.5.0 release notes](https://github.com/home-assistant-libs/chip-wheels/releases/tag/2024.5.0).

Update to Matter SDK wheels 2024.5.0

---

matter_server/server/helpers/paa_certificates.py

Fixes https://github.com/home-assistant-libs/python-matter-server/issues/704

Use mkdirs for paa_root_certs as the intermediate directories do not exist

---

Dockerfile

We already passed /data as data directory so far. Let's move the PAA credentials to that location as well so they persist over container restarts. This avoids unnecessary PAA certificates downloads for container installations.

Pass PAA certificate path by default to data directory

---

matter_server/client/client.py
matter_server/common/const.py
matter_server/common/custom_clusters.py
matter_server/common/models.py
matter_server/server/device_controller.py
scripts/generate_descriptions.py

- Refactor read_attribute so it can take both single attribute path and multiple (including wildcards)
- Move custom clusters into shared/common logic, accessible by both server and client
- Add logic to poll (required) custom clusters from the server
- Rename Eve custom cluster as its a Vendor-wide cluster, not only for Eve Energy

Refactor logic for handling Custom Clusters/Attributes

---

matter_server/server/__main__.py
matter_server/server/device_controller.py
pyproject.toml

Update the CHIP wheels to 2024.5.1 to get the new
RawAttributeUpdateCallback.
To support subscriptions for custom cluster use this new RawAttributeUpdateCallback instead of AttributeUpdateCallback. This also makes sure that we update the attributes with the same objects on initial read and subsequent subscription updates (Python types but not Cluster specific struct types etc.).

Use SetRawAttributeUpdateCallback to support custom clusters

---

matter_server/common/errors.py
matter_server/server/device_controller.py

The function _resolve_node calls GetConnectedDevice(), which effectively uses the CASE (Certificate Authenticated Session Establishment) protocol to establish a session with the device. Rename the function accordingly.
While at it, convert it to a loop and print time establishment took with higher precision (with one decimal place).

Refactor and rename _resolve_node to _establish_case_session

---

matter_server/common/custom_clusters.py
matter_server/server/device_controller.py

It turns out that the custom Eve cluster is also present on battery powered devices so polling that entire cluster is not so nice. This adjusts it so that only the energy attributes are polled instead of the whole cluster. 
Also, the "read_attribute" method was already adjusted to handle a list of paths but the poll didnt use that yet.
So this addresses that as well so for the Eve devices with the energy attributes, those attributes will be polled with a single read call which returns multiple individual attributes instead of the whole cluster.

Only Poll individual attributes in custom Eve cluster

---

matter_server/server/sdk.py

Fix passing node ID to CommissionOnNetwork and some type annotations. Also make filtering optional in commission_on_network.

Fix arguments in ChipDeviceControllerWrapper

---

dashboard/src/client/models/descriptions.ts
scripts/generate_descriptions.py

Update the descriptions.ts *used by the frontend) which is auto generated from all clusters/devicetypes and attributes definitions so it includes the Matter 1.3 ddeinfitions as well as our recent changes to the custom clusters

Update the descriptions.ts to account for latest changes

---

matter_server/server/sdk.py

The refactoring broke opening the commission window by missing out returning the Commissioning parameters. Return the Commissioning parameters again.

Fix open commissioning window

---

matter_server/server/sdk.py
pyproject.toml

API calls to the native side of the SDK which have global callback functions called from the native side in ChipStack are not re-entrant since they use a shared Future object to signal the result. Currently these are all Commissioning and the Open Commission Window APIs. They can also be identified if they call CallAsyncWithCompleteCallback internally. Make sure those are called from a single Thread only.
Also bump the SDK which contains a fix where the same Future is unnecessarily cleared/set for regular API calls. This avoid re-entrancy issues between regular API calls and the ones with callbacks from the native side.
With this, all currently known re-entrancy issues should be addressed.

Fix SDK reentrancy issues

---

matter_server/client/client.py

Technically all character strings are supposed to be valid UTF-8 strings. We've encountered devices which return non-printable characters as part of the octet string. This change makes the client more robust and not fail when encountering such strings.

Don't fail when encountering invalid strings

---

matter_server/client/client.py

Not all Thread devices seem to provide the Thread Network Diagnostics Cluster. According to the Matter specification, this cluster is optional, even for Thread devices.
This commit only parses Thread Network Diagnostics data if the cluster is present in the device.
For completeness, also make sure that Router Eligible End Device (REED) are classified as end devices too (since that is their current role).

Improve Thread network diagnostics parsing

---

matter_server/server/device_controller.py

Use the secrets module which is cryptographically secure to generate the discriminator. The discriminator probably doesn't need to be cryptographically safe, but it also doesn't hurt and gets rid of a QA exception.

Use secrets to generate the discriminator

---

matter_server/server/server.py

A debug print sneaked into the code late in review. This commit removes the print again.

Remove unnecessary debug print statements

---

matter_server/server/server.py

Create the instance of MatterDeviceController in the start() method. This makes sure that the PAA certificate fetch is done before the controller is created.
Fixes: https://github.com/home-assistant/core/issues/119145
Refs: #720

Move MatterDeviceController instantiation to start()

---

matter_server/server/device_controller.py

Don't strip the scope ID from the link-local address. The scope ID is required to ping a link-local address reliably in all network configurations.
Fixes: https://github.com/home-assistant/core/issues/119304

Fix link-local address pinging

---

matter_server/client/client.py
matter_server/common/models.py
matter_server/server/device_controller.py

This commit reintroduces the ability to get IP addresses without scope. This is useful in case we are really not interested in the scope on client side e.g. because we know we run on a different system.
There is currently not need in Home Assistant for this feature, but rather to break it for no good reason just keep it around, it might be useful for someone.

Reintroduce ability to get IP addresses without scope

---

matter_server/server/device_controller.py
matter_server/server/sdk.py
matter_server/server/stack.py
pyproject.toml

Matter SDK/CHIP wheels [2024.6.0 release notes](https://github.com/home-assistant-libs/chip-wheels/releases/tag/2024.6.0).
This mostly aligns the Matter SDK Python bindings to what is in latest master.
Probably most noteworthy is that SendCommand/GetConnectedDevice are now asyncio friendly throughout, so should never block even when the CHIP thread is very busy. No such cases have been observed, so this is mostly theoretical at this point.
Some unnecessary locking has been dropped which potentially could improve performance.
And finally, the API `TriggerResubscribeIfScheduled` on subscriptions is exposed to Python. This allows to resubscribe subscriptions quicker when a device re-appears.

Update to Matter SDK wheels 2024.6.0

---

matter_server/server/device_controller.py

Check if the commissioning window is indeed open before returning cached values. This is to prevent returning stale values when the commissioning window got closed, either because the device got successfully commissioned with another network or because the commissioning window got closed due to an error in attempting to commission. Especially the latter case leads to very bad user experience as folks try to use the stale (non-working) commissioning code for the next 10 minutes and get frustrated.
While at it, also close the commissioning window if someone else opened it and we can't provide credentials.

Improve the open commissioning window command

---

matter_server/common/custom_clusters.py

**EveCluster**
I would like to add attributes to the "EveCluster" cluster. You can see them here:
EveCluster Attributes for Eve Door:
- TimesOpened: 319422470 (0x00130a0006)

[Eve Door] EveCluster --> Attribute TimesOpened

---

pyproject.toml

Matter SDK/CHIP wheels [2024.6.1 release notes](https://github.com/home-assistant-libs/chip-wheels/releases/tag/2024.6.1).
This update improves the implementation of the commissioning API's considerably, using thread-safe Python provided futures (see https://github.com/project-chip/connectedhomeip/pull/33891). In practice it should not make a difference, as the API is still not reentrant. But it will be easier to transition to an asyncio based API.
Another notable change is that with this update mDNS discovery is disabled immediately after discovering the device in question when using the on-network commissioning mode. The on-network commissioning mode is used by both the Android and the Apple companion app. 
This prevents spurious error logs like this: `Unknown filter type; all matches …

Update to Matter SDK wheels 2024.6.1

---

matter_server/server/device_controller.py

Fixed for an edge case defect/bug when importing the first test node using the dashboard via a diagnostics file.
1) run the python matter server (no matter nodes commissioned)
2) run the dashboard node app
3) attempted to try to import a device diagnostic file
- tested with this [diagnostic file](https://gist.githubusercontent.com/oidebrett/bc8adb22da7d535a85dda163870b6bfe/raw/99c841c7f3dd1d463ce98ccbb0b718e58d0eee02/matter-260e4ed87923fb5ffd94045df082f99f-Smart%2520Plug%2520Mini-52001041c32f3b43790185078ec65ad0.json) 
4) the dashboard throws an error in device_controller.py file
`
File "/home/XXX/Projects/pip-python-matter-server/venv/lib/python3.11/site-packages/matter_server/server/device_controller.py", line 857, in import_test_node
next_test_node_id = max(*(x for x in self._nodes), …

Edge case defect when importing the first test node into dashboard

---

matter_server/server/device_controller.py
matter_server/server/sdk.py
pyproject.toml

Changes required to use the new co-routines based Matter SDK API.

Convert to asyncio Matter SDK API

---

matter_server/common/helpers/util.py
matter_server/server/device_controller.py
tests/common/test_parser.py

Some Matter Attributes require sending a Null value to reset it to its device/factory default.
This was not working correctly, especially in the case if the annotation was a union (e/.g. an optional int).
This issue is now fixed so the write_attribute can correctly understand that it actually needs to write the sdk's Null if python sends a None.
Also added a quick test case

Fix writing of Nullable attributes

---

matter_server/common/custom_clusters.py

I added a custom cluster definition for energy consumption data that the Neo Coolcam Matter smart plug measures and writes to this cluster.
However the raw values for voltage and watt will need additional scaling, the voltage raw value for e.g. 227.3 V is "2273", the watt raw value for e.g. 10.1 W is "101". Current is reported in mA. Wattaccumulated is reported in Wh, however the time frame for each accumulation measurement does not seem to be constant.  
In addition I could not yet find a raw value for total energy consumption, even so the Tuya app reports such a value.

Added custom cluster for energy consumption data for Neo smart plug

---

matter_server/server/server.py

All calls to signal_event are made in the asyncio event loop thread. Therefore, we don't need to use the threadsafe variant of call_soon() anymore.
This was anyways a bit brittle as asyncio.create_task() is not threadsafe, so calling signal_event from a different thread was not really safe.

Don't use threadsafe variant in signal_event

---

matter_server/server/device_controller.py
matter_server/server/sdk.py

Override the liveness timeout when a node announces a shutdown. This causes the subscription logic to notice that the device went offline much quicker, which is especially nice for battery operated devices which have a high liveness timeout.
We use 5s as timeout to make sure the device really completed shutdown, and that the first subscription resumption triggered by this actually fails. We can restore the timeout to default immediately after, since the SDK is in subscription resumption mode now.
Another alternative would be to shutdown the subscription (mark the device as offline). This has the disadvantage that the controller needs to recreate the subscription from scratch when it comes back, which causes unnecessary traffic.
If the node stays offline for longer than 30s, we'll still …

Override Liveness timeout on shutdown

---

matter_server/client/client.py
matter_server/client/connection.py
matter_server/client/exceptions.py
matter_server/server/server.py

Currently InvalidServerVersion was only raised when the client was too old (Server wasn't able to handle such an old client anymore), e.g. after a backwards incompatible change Server side.
However, if the client was newer than the Server schema version, no error was raised. This essentially never triggered the add-on update logic in Core.
This change makes sure that we raise InvalidServerVersion when the Server is too old for the client too. We also add properties to the Exception so a client can figure out which situation we are dealing with (too old/too new) and act accordingly.

Raise InvalidServerVersion when Server is too old too

---

matter_server/server/sdk.py

Instead of using find_or_establish_case_session use the GetConnectedDevice API directly to get a device proxy for attribute reads. This has the advantage that it runs in a single node lock. With that we no longer will try to establish a case session multiple times though.

Use GetConnectedDevice directly to get device proxy

---

pyproject.toml

Matter SDK/CHIP wheels [2024.6.3 release notes](https://github.com/home-assistant-libs/chip-wheels/releases/tag/2024.6.3).
This lifts the connected device limit from 64 to 1024.

Update to Matter SDK wheels 2024.6.3

---

matter_server/server/sdk.py
pyproject.toml

Matter SDK/CHIP wheels [2024.6.4 release notes](https://github.com/home-assistant-libs/chip-wheels/releases/tag/2024.6.4).
This correctly lifts the connected device limit from 64 to 1024.
It also converts DiscoverCommissionableNodes() to an async API.

Update to Matter SDK wheels 2024.6.4

---

pyproject.toml

This increases the secure session limit to 4096 which should allow subscriptions for more than the previous limit of 50 devices simultaneously.

Update to Matter SDK wheels 2024.7.0

---

compose.yml

The [new Docker Compose Specification](https://docs.docker.com/compose/compose-file/04-version-and-name/) makes obsolete the version top-level element

Update compose.yml to follow new Compose Specification

---

matter_server/server/__main__.py
matter_server/server/helpers/paa_certificates.py
matter_server/server/server.py

Currently we fetch PAA certificates from the test-net DCL server by default. Often these are the same certificates as the production DCL, so this doesn't really have that much impact. However, those certs are really only required for development as certified devices will be present on the production DCL.
In the future we'll fetch more information from the DCL such as device update information etc. For these cases we really don't want production users to use test-net DCL by default.
This moves test-net DCL use behind a flag. By default this should be off.

Add flag for test-net DCL

---

matter_server/server/__main__.py

This change converts the `--enable-test-net-dcl` command line argument to a flag which is much more natural for a boolean argument.

Convert --enable-test-net-dcl to a flag argument

---

matter_server/common/custom_clusters.py

[ThirdReality Private Metering cluster server.pdf](https://github.com/user-attachments/files/16085505/ThirdReality.Private.Metering.cluster.server.pdf)
I only implemented the energy and power metering attributes

Add custom cluster definition for ThirdReality Energy reporting

---

Dockerfile.dev

Fix for https://github.com/home-assistant-libs/python-matter-server/issues/776

Enable dashboard in dev build

---

matter_server/server/device_controller.py

If you have issues in your Thread network and/or multiple misbehaving devices we get trapped into a deadlock situation if we have 5 nodes stuck in setup. In that case no devices will be setup at all.
This changes the logic a tiny bit so we still use a semaphore to somewhat throttle the burst of traffic that the setup generates on the thread network but back out of it in case a node hangs in there.
- Use set-up semaphore only for Thread devices
- Release semaphore when we detect a node hangs in setup

A small optimization to the node setup

---

matter_server/common/models.py
matter_server/server/__main__.py
matter_server/server/device_controller.py
matter_server/server/server.py
matter_server/server/stack.py

Add (explicit) support for commissioning using Bluetooth next to on-network commissioning.
Because it can be very unstable for some bluetooth adapters (like the pi builtin adapter for example), it requires a specific bluetooth adapter id/index

Add direct bluetooth commissioning support

---

Dockerfile
matter_server/client/client.py
matter_server/common/const.py
matter_server/common/errors.py
matter_server/common/models.py
matter_server/server/__main__.py
matter_server/server/const.py
matter_server/server/device_controller.py
matter_server/server/helpers/__init__.py
matter_server/server/helpers/paa_certificates.py
matter_server/server/ota/__init__.py
matter_server/server/ota/dcl.py
matter_server/server/ota/provider.py
matter_server/server/server.py
tests/server/ota/test_dcl.py

This adds software update capability to the Python Matter Server.
As it stands, the implementation does the following things:
1. Check the DCL for software updates for a particular device
2. If an update is available, it downloads the firmware locally
3. Prepares the OTA Provider on the Matter fabric (using the Linux OTA Provider example app)
3a. On first use, the OTA Provider App is first commissioned to the fabric
4. Notifies the node about the availability of the OTA Provider and the update
The node then communicates directly with the OTA Provider. Progress of the update can be observed in the OTA Software Update Requestor Cluster of the device being updated.
There are a few things which still need to be sorted out:

Add software update capability

---

matter_server/common/models.py
matter_server/server/ota/provider.py

Make sure parent directories get created to when creating the node specific update directory.
Fix save/restore of the UpdateSource.

Matter update fixes

---

pyproject.toml

This fixes Subscription issues. Mainly it avoids being stuck in subscription setup if there is a communication issue with the device.
Fixes: #807

Update to Matter SDK wheels 2024.7.1

---

matter_server/server/ota/dcl.py
pyproject.toml
tests/server/ota/fixtures/4447-8194-1000.json
tests/server/ota/fixtures/4447-8194-1011-invalid.json
tests/server/ota/fixtures/4447-8194-1011-valid.json
tests/server/ota/fixtures/4447-8194.json
tests/server/ota/test_dcl.py

Skip updates which have the softwareVersionValid flag set to false. This avoids flashing potentially invalid software versions to Matter devices.

Skip updates from DCL which are considered invalid

---

matter_server/server/stack.py

This enables server cluster interactions on a controller. But currently more importantly, it enables advertisement of active controller operational identities, or in other words, it makes sure that the controller publishes a mDNS/DNS-SD operational discovery service.
This is required for persistent subscriptions to work: Matter devices which support persistent subscriptions (e.g. Nanoleaf bulbs) will try to reestablish the subscriptions right after startup. For that to work they need to resolve the controller through operational discovery.
In other words, with this change nodes come much quicker available/controllable when they restart.

Enable server interactions by default

---

Dockerfile

OTA Provider to 2024.7.2 increases the number of network endpoints supported. This makes the OTA Provider work on systems with many add-ons/network interfaces just like the controller itself.

Bump OTA Provider to 2024.7.2

---

matter_server/server/ota/provider.py

The OTA checksum is base64 encoded, whitespaces at the start or end are not part of the checksum. Simply strip them before comparing.
Fixes: #817

Trim OTA checksum for whitespace before comparing

---

README.md
compose.yml

Our Dockerfile uses the CMD instruction to run the server with sensible default arguments. Often folks forget to add those when customizing their command. This adds a note to the README.md and the compose.yml file to remind them.
This also removes the D-Bus access in the default startup example since D-Bus is only required for Bluetooth support (which is no longer enabled by default). An additional example with the correct command line and D-Bus access should make it clear what needs to be done to restore previous behavior.

Add note about Docker default command

---

matter_server/server/server.py

Add a log entry with info level when the Matter server finishes startup. This is useful to know when the server is ready and starts event based Node setup processing (from mDNS events).
Helps for situation like https://github.com/home-assistant/core/issues/121932

Log when the Matter server finished startup

---

matter_server/common/helpers/util.py
tests/common/test_parser.py

Fix writing an attribute value to 'null' which is marked as optional 'None'.
Bit of an edge case but I ran into it with the `OnOff.Attributes.StartUpOnOff` attribute which is typed as `typing.Union[None, Nullable, OnOff.Enums.StartUpOnOffEnum]`
To set it to defaults, you need to send an explicit null

Fix writing optional Nullable values

---

matter_server/server/device_controller.py
matter_server/server/ota/dcl.py
tests/server/ota/fixtures/4442-67-197888.json
tests/server/ota/fixtures/4442-67-197910.json
tests/server/ota/fixtures/4442-67-198340.json
tests/server/ota/fixtures/4442-67.json
tests/server/ota/test_dcl.py

Skip updates which don't have an URL. We can't update such a node, so simply pretend as if they don't exist in the version info.

Don't regard update information without a valid URL

---

matter_server/server/device_controller.py

Previous commit added an update check with wrong syntax. Fix the syntax to make update check work again.

Fix OTA URL check syntax

---

dashboard/src/client/client.ts
dashboard/src/client/connection.ts
dashboard/src/client/models/descriptions.ts
dashboard/src/pages/matter-dashboard-app.ts

Catch a lost connection in the dashboard, otherwise you are looking at stale data and actions silently fail.
No fancy reconnect logic, just a page that the connection was lost.

Handle lost connection in the dashboard

---

matter_server/common/custom_clusters.py

Update custom_clusters.py to add Eve Weather pressure attribute
- EveCluster -> AttributeId: 319422483 (0x00130a0013) --> altitude
- EveCluster -> AttributeId: 319422484 (0x00130a0014) --> pressure
**Dump file**
[matter-2a4bd9d95d966aefd2521cccecaf2a8f-Eve Weather 20EBS9901-4b1740986a8ca70f15a63d1d0d6a1e02.json](https://github.com/user-attachments/files/16461658/matter-2a4bd9d95d966aefd2521cccecaf2a8f-Eve.Weather.20EBS9901-4b1740986a8ca70f15a63d1d0d6a1e02.json)

Add Eve Weather custom attributes

---

matter_server/common/custom_clusters.py

Add Class attribute for Eve Cluster (EveWeather device):
- Altitude
- Pressure
HA core PR: [Add EveWeatherPressure attribute #123565](https://github.com/home-assistant/core/pull/123565)

Eve cluster part2: Add EveWeather attributes

---

matter_server/server/helpers/paa_certificates.py

Simply rely on the default, until we have a good reason to customize this timeout.

Drop custom timeout on PAA get request

---

matter_server/server/device_controller.py

With the update of the Matter SDK wheels to 2024.7.1 (#809) the SDK no longer auto-resubscribes when the read of the subscription fails (see https://github.com/project-chip/connectedhomeip/pull/34370). The Server had a comment that it relies on mDNS rediscovery to re-establish the subscription. But this is not always the case. This change adds a retry mechanism to the subscription setup for a fixed period of time after seeing it via mDNS.
Additionally, it avoids recreating the subscription if the liveness timeout did not occur yet. This puts more trust into the SDK handling the subscriptions.
Fixes: https://github.com/home-assistant/core/issues/124503

Retry subscription setup if necessary

---

matter_server/server/device_controller.py

On first setup, we create a task and the task will remain in the task list. If a node gets offline and rediscovered on mDNS again, we will need to setup the node again. In this case we'll have that previous task, but it will be done. So check if the task is done and if so allow starting another setup task.
Fixes introduced in #873.

Check if setup task is actually still running

---

matter_server/server/device_controller.py

Instead of relying on the progressively growing and random resubscribe interval simply check the time since the first re-subscription attempt.
The resubscribe interval is chosen at random, and even in the terminal state, a resubscription potentially happens below 30 minutes (in the final progression the resubscription time is chosen at random between 27 and 92 minutes). This means that in theory we shutdown the subscription much later than actually intended.

Shutdown subscription after exactly 30 minutes

---

matter_server/server/device_controller.py

Since #809 initial subscriptions error out if there is a communication issue. This makes the subscription callback return alway at some point, even if there are communication issues.
This makes the setup node timer unnecessary. So drop this code.

Cleanup: Drop setup node timer

---

matter_server/server/device_controller.py

The fallback node scanner introduced with #603 intents to pick up nodes which our zeroconf scanner missed. There is currently no indication that the zeroconf scanner misses nodes (anymore), so the fallback scanner is redundant. This PR removes the fallback scanner.

Cleanup: Remove fallback node scanner

---

matter_server/server/device_controller.py
matter_server/server/ota/provider.py

Support local update file for Matter OTA updates. The otaUrl must use the file:/// URL scheme. The path is relative to the OTA provider directory.

Support local update file for OTA

---

matter_server/server/ota/provider.py

Instead of using a fixed port for OTA Provider, pass 0 to let the Matter SDK/bind() syscall select a random port. This allows multiple OTA Providers to run on the same host without port conflicts.
Fixes: https://github.com/home-assistant/core/issues/125130

Select OTA Provider port randomly

---

matter_server/server/ota/provider.py

Use asyncio.to_thread where appropriate, and replace existing loop.run_in_executor() calls with the shorter asyncio.to_thread() call.

Use to_thread where appropriate

---

matter_server/common/custom_clusters.py

`MotionSensitivity` attribute within the Eve Cluster
**AttributeId: 319422477** (0x00130a000d)
- 0 High
- 4 Medium
- 7 Low

MotionSensitivity attribute within the Eve Cluster

---

matter_server/server/sdk.py
pyproject.toml

The 2024.9.0 wheels come with an improved attribute cache handling: The Attribute cache only gets updated when actually uesd. This will save Attribute cache updates in Subscriptions typically, and moves Attribute cache updates for reads out of the SDK thread.

Update to Matter SDK wheels 2024.9.0

---

matter_server/server/device_controller.py

Yesterday we updated the mininterval floor to 1 second, to prevent a flood of updates at an insane frequency (e.g. transitions) but apparently this is not recommended for ICD devices.
So small follow-up to use 0 for ICD and 1 second for all other.

Use interval floor of 0 for ICD devices

---

matter_server/common/custom_clusters.py

The server has some logic to poll custom attributes when needed, this is for example needed for the custom power/energy attributes on Eve Energy with firmware version < 3.5.
The newer Eve Energy firmware however implements the official Matter 1.3 clusters for power and energy measurements so no need to to poll these attributes anymore.
- Changes should_poll in the custom cluster/attribute definitions into a method/callback that accepts the MatterNodeData as argument. That way the implementation can do some conditional checks based on node attribute/firmware version etc.
- Disable polling if the node is not Eve - this catches e.g. the MatterBridge which (ab)uses the Eve custom cluster to send power measurements. There is no reason to poll those values.
- Disable polling on the Eve power …

Prevent Eve devices with newer firmware to be polled

---

matter_server/client/client.py
matter_server/common/const.py
matter_server/common/models.py
matter_server/server/device_controller.py

Add a fabric label right after commissioning. This will make it easier for other platforms to identify what particular fabrics a device is commissioned with.

Add fabric label on commissioning

---

matter_server/server/device_controller.py
matter_server/server/ota/provider.py

In case the subscription of the device gets shutdown, stop the update process and return an error to the client.

Abort update when device goes offline

---

README.md

Updates the README, moving the OHF badge to underneath the first section to ensure it isn't lost due to the length of the README

Moved OHF badge to suitable location in README

---

matter_server/server/device_controller.py

When triggering an interview update the Fabric label on the device as well. This allows users to update the label by a simple re-interview.

Update label on interview

---

dashboard/README.md

Fix websocket server port in dashboard README.
Fixes #961

Fix websocket server port in dashboard README

---

README.md

Add Manual pairing code in README

Add Manual pairing code in README

---

README.md

Move the Python example a little further in README

(fix/doc) Move the Python example a little further in README

---

Dockerfile

The latest latest build of Matter/CHIP wheels v2024.11.0 require a newer Debian version. This is required because the CHIP wheels build uses the Matter SDK build system, which recently got updated to Ubuntu 24.04. This meant that the native library got linked against a newer glibc version.
Technically, the Python 3.12 update is not related/strictly required. But it seems that the Matter v1.3 version of Matter/CHIP wheels v2024.9.0 runs fine with Python 3.12 already. So it is safe to upgrade the two at once.

Bump container base image to Debian 12 and Python 3.12

---

README.md

Fix formatting for 'Manual pairing code' section

Fix formatting for 'Manual pairing code' section

---

dashboard/src/client/models/descriptions.ts
matter_server/client/models/device_types.py
matter_server/client/models/node.py
pyproject.toml

The Matter 1.4 wheels are built against a glibc version that is too new.
We need to revert the bump to 1.4 for now until we resolve that.

Revert bump to Matter 1.4 wheels and device types

---

dashboard/src/client/models/descriptions.ts
matter_server/client/models/device_types.py
matter_server/client/models/node.py
pyproject.toml

Ues the lastest CHIP wheels which are linked against glibc from Debian 12.
This effectively reverts commit a55bb8b0dc838cfee2eb0dd70f18655e26540efb again.
BREAKING change in the client: BridgedDevice is renamed to BridgedNode in the device types

Bump to Matter 1.4 wheels and device types

---

README.md

Explain how to start the server in debug log-level

Explain how to start the server with debug log-level

---

dashboard/src/client/models/descriptions.ts
matter_server/common/custom_clusters.py

Yandex Smart Socket ([YNDX-00540](https://csa-iot.org/csa_product/yandex-smart-socket/)) use ElectricalMeasurement cluster that was in draft Matter specification but not made in 1.0 spec. It was finally removed in v1.4 branch of Matter SDK (see https://github.com/project-chip/connectedhomeip/pull/35583). 
HA pull request that will use this cluster: https://github.com/home-assistant/core/pull/132920

Add draft ElectricalMeasurement cluster definition

---

matter_server/server/device_controller.py

Instead of setting the label on commissioning only, set it during the interview process but only if necessary. This avoids the commissioning process to fail in a incomplete state when setting the label fails.
The interview process has more resilience to recover from a failure during the commissioning since we have a retry mechanism in place.
This also allows to set the label on devices that are already commissioned.
Also (try to) unpair the device in case interviewing fails. This allows user to commission a second time without running into "Trying to add a NOC for a fabric that already exists" errors.

Set fabric label on interview

---

matter_server/server/storage.py
pyproject.toml

Prevent our persistent storage file get corrupted if writing fails or power is cut during writing.
This is step 1 because a similar approach is also needed for the sdk's json file which contains the fabric (cryptographic) data.
Related to #977

Use atomic writes for the storage file

---

matter_server/server/storage.py

Small oversight in the last change: At the very first start, there is no original file at all (yet) that can be backupped.
Fixes #1018

Fix settings file storage at first/clean startup

---

.pre-commit-config.yaml

Since 3.2.0 the stage names match the hook names. Change the stage names accordingly (see also https://pre-commit.com/#confining-hooks-to-run-at-certain-stages).

Use new pre-commit stage names

---

matter_server/server/device_controller.py
matter_server/server/ota/__init__.py

For development it is sometimes useful to just reuse the same version string but increment the underlying build number (which is the actual version devices typically care about).
This change supports multiple local updates with the same version string, and updating to an explicit version by version integer.

Support local updates with the same version string

---

.github/workflows/pr-labels.yaml

Allow docs as label which is useful for PRs only touching README.md/docs directory.

Add docs to allowed PR labels

---

dashboard/src/client/models/descriptions.ts
matter_server/common/custom_clusters.py

Adding an additional attribute to the inovelli custom cluster at the request of @jvmahon
https://community.inovelli.com/t/possible-to-automate-led-indicator-intensity-on-white-series/18651/14?u=harryh

Add additional attribute to Inovelli VTM31-SN dimmer custom cluster

---

matter_server/server/device_controller.py

The unicast service discovery leads to unicast responses. However, only a single process can receive a unicast response. This is a problem since the Matter Server is most likely not the only mDNS client on a given host.
By default, the service discovery starts with an unicast request first and continues with multicast requests from then onwards (the first multicast request is sent about 200ms later). So service discovery worked with the default initialization too. But with this change we get rid of the unicast request speeding up the service discovery slightly.

Always use multicasts for service discovery

---

Dockerfile

This updates the OTA provider to the latest v1.4-branch version of the Matter SDK.

Bump OTA Provider to 2025.5.0

---

.github/workflows/test.yml

The library was a requirement of the CHIP Python REPL (iirc), which is not being used for tests.

Remove unnecessary libgirepository dependency

---

scripts/generate_devices.py

The Poll Control cluster got removed a while ago, so just get rid of the workaround.

Drop temporary workaround for Poll Control

---

dashboard/src/client/models/descriptions.ts
matter_server/client/models/device_types.py

Adding the new mounted device types (1.4).

Add Mounted device types (1.4)

---

.pre-commit-config.yaml
matter_server/server/device_controller.py
matter_server/server/server.py
tests/test_device_controller.py

Services are now parsed in a more robust way, to avoid issues in cases where the service name is not exactly as expected. This has been observed to be the case for Thread devices, presumably because two Thread border routers attempt to announce the same service name. The service name then becomes a " (2)" suffix, which the old code did not handle well.
We could parse this duplicated messages as well, but generally only a single node should ever announce a service name. If a service name gets announced by two independent devices, the two services likely stem from the same underlying device but simply got duplicated by some environmental factor (e.g. Thread border routers not being in sync on who announces the service name, or badly configured mDNS reflectors duplicating messages on the …

Improve Matter DNS-SD service parsing

---

dashboard/note.md
dashboard/src/client/client.ts
dashboard/src/client/models/model.ts
dashboard/src/components/dialogs/acl/model.ts
dashboard/src/components/dialogs/binding/model.ts
dashboard/src/components/dialogs/binding/node-binding-dialog.ts
dashboard/src/components/dialogs/binding/show-node-binding-dialog.ts
dashboard/src/pages/components/context.ts
dashboard/src/pages/components/node-details.ts
dashboard/src/pages/matter-cluster-view.ts
matter_server/common/models.py
matter_server/server/device_controller.py

I added a button in the binding cluster of the node to add the binding relationship of the device.
Note: Currently, binding to the endpoints of the device is only supported.
I conducted tests using [light_switch](https://github.com/espressif/esp-matter/tree/main/examples/light_switch) and [light](https://github.com/espressif/esp-matter/tree/main/examples/light) in the esp-matter sdk, and the test results met the requirements.
(One-to-one endpoint control can be achieved, as well as one-to-many endpoint control.)
The operation is as follows
1. Enter the binding cluster of the node, and a 'Binding' button will appear on it.
2. After clicking the 'Binding' button, you can add or delete binding relationships.
As shown in the following figure:

add node binding dialog.

---

pyproject.toml

The Matter SDK wheels have been updated to version 2025.7.0, which is built from the v1.4.2 branch of the Matter SDK repository.
See [2025.7.0 release](https://github.com/home-assistant-libs/chip-wheels/releases/tag/2025.7.0).

Update to Matter SDK wheels 2025.7.0

---

matter_server/server/server.py

The Matter SDK initializes the network diagnostic cluster on startup which prints its own primary interface name. This leads to confusion to what primary interface the Matter Server itself is using. Print the primary interface used by the Python Matter server separately as well.
See https://github.com/home-assistant/addons/pull/4092#issuecomment-3164029245

Log primary interface used by Python Matter server on startup

---

matter_server/common/custom_clusters.py

For Eve MotionBlinds, `ObstructionDetected` attribute within the Eve Cluster
`Boolean obstructionDetected 319422480 / AttributeId: 319422480 (0x00130a0010)`

ObstructionDetected Attribute within the Eve Cluster

---

Dockerfile

This updates the OTA provider to the latest v1.4.2-branch version of the Matter SDK.
See [2025.9.0 change log](https://github.com/home-assistant-libs/matter-linux-ota-provider/releases/tag/2025.9.0).

Bump OTA Provider to 2025.9.0

---

docs/docker.md

Update Docker image reference for Matter server container image
